### ISSUE TITLE
setBaseDir() method

### ISSUE THREAD

**Issue by rogerta** [Guichaguri/hogan-cached#3]
This is a question about the need for the `setBaseDir()` method.

`setBaseDir()` sets the `options.basedir` global variable.  This variable is used only if `options.settings['views']` returns falsy.  However, `options.settings['views']` can never be falsy.

In most cases, users of express will call `app.set('views', <dir-of-views>)` with a directory string.  If not called explicitly, express defaults to the directory `'views'`.  In theory a user could call `app.set('views', null)`, but then express crashes before even calling into the template engine.

Seems like this method and the `options.basedir` global variable could be deleted and the code simplified.

**Comment by Guichaguri** [comment]
Yes, I think so.
I don't really remember why I've added `setBaseDir()`. I think it was before I changed a bunch of stuff, and at that time the function was needed for whatever reason
